### ISSUE TITLE
App crash on macOs High Sierra

### ISSUE THREAD

**Issue by Estayparadox** [naman14/Muzei-macOS#3]
Muzei crashed when I added the "Terra" tag then I couldn't open it anymore.
So I've deleted all related files and the app and downloaded it for the second time and now I can't use reddit and my app settings are not saved, I think preferences are not updated...

**Comment by Estayparadox** [comment]
Ok, so I've deleted all related files and the app then I've  downloaded the app and now I can't use reddit and my app settings are not saved

**Comment by Estayparadox** [comment]
<img width="714" alt="capture d ecran 2018-04-18 a 15 00 51" src="https://user-images.githubusercontent.com/19834789/38933512-71d80c04-4319-11e8-89d5-3b8edf6634de.png">
<img width="1027" alt="capture d ecran 2018-04-18 a 15 01 01" src="https://user-images.githubusercontent.com/19834789/38933513-73fefc18-4319-11e8-8cdd-7e8bf7b8c37a.png">

**Comment by naman14** [comment]
Should be fixed in the new release
